using Microsoft.Win32;
using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;

namespace LogAnalyzer
{
  /// <summary>
  /// Interaction logic for MainWindow.xaml
  /// </summary>
  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();
    }

    private void OpenConfig_Click(object sender, RoutedEventArgs e)
    {
      OpenFileDialog dialog = new OpenFileDialog();

      dialog.Filter = "Configuration files|*.config";

      if (dialog.ShowDialog(this) == true)
        ((TablePresenter)this.DataContext).OpenConfig(dialog.FileName);
    }

    private void OpenFile_Click(object sender, RoutedEventArgs e)
    {
      OpenFileDialog dialog = new OpenFileDialog();

      dialog.Filter = "Log files|*.log";

      if (dialog.ShowDialog(this) == true)
        ((TablePresenter)this.DataContext).OpenLog(dialog.FileName);
    }

    private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
    {
      var grid = (DataGrid)sender;

      if (grid.Columns.Count > 0)
        grid.Columns[grid.Columns.Count - 1].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
      if (grid.Columns.Count > 1)
        grid.Columns[grid.Columns.Count - 2].Width = new DataGridLength(1, DataGridLengthUnitType.Star);
    }

    private void FilterRow_TextChanged(object sender, TextChangedEventArgs e)
    {
      var ctrl = sender as TextBox;

      var obj= ctrl.TemplatedParent as DataGridColumnHeader;

      var name = ((Binding)((DataGridBoundColumn)obj.Column).Binding).Path.Path;

      ((TablePresenter)this.DataContext).SetFilter(name, ctrl.Text);
    }

    private void MenuItemClose_Click(object sender, RoutedEventArgs e)
    {
      var button = sender as Button;
      var obj = button.TemplatedParent as ListBoxItem;
      ((TablePresenter)this.DataContext).ClosePage(obj.Content as FileEntry);
    }
  }
}
