//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notung.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notung.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Component type &quot;{0}&quot; is abstract.
        /// </summary>
        internal static string ABSTRACT_COMPONENT_TYPE {
            get {
                return ResourceManager.GetString("ABSTRACT_COMPONENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to find any suitable alternative for duplicates.
        /// </summary>
        internal static string BAD_DUPLICATES {
            get {
                return ResourceManager.GetString("BAD_DUPLICATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key &apos;{0}&apos; is reserved.
        /// </summary>
        internal static string CONTEXT_KEY_RESERVED {
            get {
                return ResourceManager.GetString("CONTEXT_KEY_RESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon DotChart {
            get {
                object obj = ResourceManager.GetObject("DotChart", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Another configuration section {0} already has the same name as {1}.
        /// </summary>
        internal static string DUPLICATE_SECTION_NAME {
            get {
                return ResourceManager.GetString("DUPLICATE_SECTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default logger cannot be empty or whitespace.
        /// </summary>
        internal static string EMPTY_DEFAULT_LOGGER {
            get {
                return ResourceManager.GetString("EMPTY_DEFAULT_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arc cycle detected. Unable to perform topological sort.
        /// </summary>
        internal static string GRAPH_CYCLE {
            get {
                return ResourceManager.GetString("GRAPH_CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph must be oriented for topologogical sort.
        /// </summary>
        internal static string GRAPH_MUST_BE_ORIENTED {
            get {
                return ResourceManager.GetString("GRAPH_MUST_BE_ORIENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This collection needs to be be fixed, but it is impossible, because it has fixed size.
        /// </summary>
        internal static string IMPOSSIBLE_FIX {
            get {
                return ResourceManager.GetString("IMPOSSIBLE_FIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration section must be a non-abstract class with paramrterless constructor and inherited from Toolbox.Configuration.ConfigurationSection.
        /// </summary>
        internal static string INVALID_CONFIG_SECTION_TYPE {
            get {
                return ResourceManager.GetString("INVALID_CONFIG_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delegate type {0} is not recognized as EventHandler&lt;{1}&gt;.
        /// </summary>
        internal static string INVALID_EVENT_HANDLER {
            get {
                return ResourceManager.GetString("INVALID_EVENT_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plugins directory path must be relative.
        /// </summary>
        internal static string INVALID_PLUGIN_DIRECTORY {
            get {
                return ResourceManager.GetString("INVALID_PLUGIN_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} is not a correct plugin file.
        /// </summary>
        internal static string INVALID_PLUGIN_FILE {
            get {
                return ResourceManager.GetString("INVALID_PLUGIN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server doesn&apos;t support operation {0}.
        /// </summary>
        internal static string INVALID_SERVER_OPERATION {
            get {
                return ResourceManager.GetString("INVALID_SERVER_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly {0} specified in plugin file {1} does not exist.
        /// </summary>
        internal static string PLUGIN_NOT_FOUND {
            get {
                return ResourceManager.GetString("PLUGIN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to save inherited section. Expected type {0}, actual type {1}.
        /// </summary>
        internal static string SECTION_TYPE_UNINHERITABLE {
            get {
                return ResourceManager.GetString("SECTION_TYPE_UNINHERITABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings restore started.
        /// </summary>
        internal static string SETTINGS_RESTORE {
            get {
                return ResourceManager.GetString("SETTINGS_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stream flush.
        /// </summary>
        internal static string STREAM_FLUSH {
            get {
                return ResourceManager.GetString("STREAM_FLUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some critical errors leaded to stop. View detail descripton for all messages to explain.
        /// </summary>
        internal static string SUMMARY_ERROR {
            get {
                return ResourceManager.GetString("SUMMARY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на These messages contain only information and does not require anithing to do.
        /// </summary>
        internal static string SUMMARY_INFO {
            get {
                return ResourceManager.GetString("SUMMARY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read these warnings and fix the problems detected.
        /// </summary>
        internal static string SUMMARY_WARNING {
            get {
                return ResourceManager.GetString("SUMMARY_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thread context can be edited only in thread where it was created.
        /// </summary>
        internal static string THREAD_CONTEXT_MISMATCH {
            get {
                return ResourceManager.GetString("THREAD_CONTEXT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This plugin was not loaded correctly. It cannot be unloaded.
        /// </summary>
        internal static string UNLOAD_PLUGIN_NO_CONTAINER {
            get {
                return ResourceManager.GetString("UNLOAD_PLUGIN_NO_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to unload plugin from the current appliation domain.
        /// </summary>
        internal static string UNLOADING_PLUGIN_CURRENT_DOMAIN {
            get {
                return ResourceManager.GetString("UNLOADING_PLUGIN_CURRENT_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name contains wrong symbols.
        /// </summary>
        internal static string WRONG_FILE_SYMBOLS {
            get {
                return ResourceManager.GetString("WRONG_FILE_SYMBOLS", resourceCulture);
            }
        }
    }
}
