//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schicksal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchicksalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchicksalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schicksal.SchicksalResources", typeof(SchicksalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string BOOL {
            get {
                return ResourceManager.GetString("BOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consictency.
        /// </summary>
        public static string CONSISTENCY {
            get {
                return ResourceManager.GetString("CONSISTENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string COUNT {
            get {
                return ResourceManager.GetString("COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string DECIMAL {
            get {
                return ResourceManager.GetString("DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real (double precision).
        /// </summary>
        public static string DOUBLE {
            get {
                return ResourceManager.GetString("DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent.
        /// </summary>
        public static string EXPONENT {
            get {
                return ResourceManager.GetString("EXPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real (single precision).
        /// </summary>
        public static string FLOAT {
            get {
                return ResourceManager.GetString("FLOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heteroscedasticity.
        /// </summary>
        public static string HETEROSCEDASTICITY {
            get {
                return ResourceManager.GetString("HETEROSCEDASTICITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperbola.
        /// </summary>
        public static string HYPERBOLIC {
            get {
                return ResourceManager.GetString("HYPERBOLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinity.
        /// </summary>
        public static string INFINITY {
            get {
                return ResourceManager.GetString("INFINITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer ({0} - {1}).
        /// </summary>
        public static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence interval.
        /// </summary>
        public static string INTERVAL {
            get {
                return ResourceManager.GetString("INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight line.
        /// </summary>
        public static string LINEAR {
            get {
                return ResourceManager.GetString("LINEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string MAX {
            get {
                return ResourceManager.GetString("MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string MEAN {
            get {
                return ResourceManager.GetString("MEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string MEDIAN {
            get {
                return ResourceManager.GetString("MEDIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michaelis&apos;s curve.
        /// </summary>
        public static string MICHAELIS {
            get {
                return ResourceManager.GetString("MICHAELIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parabola.
        /// </summary>
        public static string PARABOLIC {
            get {
                return ResourceManager.GetString("PARABOLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard error.
        /// </summary>
        public static string STD_ERROR {
            get {
                return ResourceManager.GetString("STD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string SYMBOL {
            get {
                return ResourceManager.GetString("SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned integer (0 - {0}).
        /// </summary>
        public static string UINT {
            get {
                return ResourceManager.GetString("UINT", resourceCulture);
            }
        }
    }
}
