//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schicksal {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchicksalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchicksalResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schicksal.SchicksalResources", typeof(SchicksalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Boolean.
        /// </summary>
        public static string BOOL {
            get {
                return ResourceManager.GetString("BOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cartis.
        /// </summary>
        public static string CARTIS {
            get {
                return ResourceManager.GetString("CARTIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cciMST.
        /// </summary>
        public static string CCIMST {
            get {
                return ResourceManager.GetString("CCIMST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chebyshev.
        /// </summary>
        public static string CHEBYSHEV {
            get {
                return ResourceManager.GetString("CHEBYSHEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consictency.
        /// </summary>
        public static string CONSISTENCY {
            get {
                return ResourceManager.GetString("CONSISTENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count.
        /// </summary>
        public static string COUNT {
            get {
                return ResourceManager.GetString("COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Money.
        /// </summary>
        public static string DECIMAL {
            get {
                return ResourceManager.GetString("DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Real (double precision).
        /// </summary>
        public static string DOUBLE {
            get {
                return ResourceManager.GetString("DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Euclidian.
        /// </summary>
        public static string EUCLIDIAN {
            get {
                return ResourceManager.GetString("EUCLIDIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exponent.
        /// </summary>
        public static string EXPONENT {
            get {
                return ResourceManager.GetString("EXPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Real (single precision).
        /// </summary>
        public static string FLOAT {
            get {
                return ResourceManager.GetString("FLOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heteroscedasticity.
        /// </summary>
        public static string HETEROSCEDASTICITY {
            get {
                return ResourceManager.GetString("HETEROSCEDASTICITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hyperbola.
        /// </summary>
        public static string HYPERBOLIC {
            get {
                return ResourceManager.GetString("HYPERBOLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Infinity.
        /// </summary>
        public static string INFINITY {
            get {
                return ResourceManager.GetString("INFINITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integer ({0} - {1}).
        /// </summary>
        public static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confidence interval.
        /// </summary>
        public static string INTERVAL {
            get {
                return ResourceManager.GetString("INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Straight line.
        /// </summary>
        public static string LINEAR {
            get {
                return ResourceManager.GetString("LINEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logistic curve.
        /// </summary>
        public static string LOGISTIC {
            get {
                return ResourceManager.GetString("LOGISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manhattan.
        /// </summary>
        public static string MANHATTAN {
            get {
                return ResourceManager.GetString("MANHATTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum.
        /// </summary>
        public static string MAX {
            get {
                return ResourceManager.GetString("MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mean.
        /// </summary>
        public static string MEAN {
            get {
                return ResourceManager.GetString("MEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Median.
        /// </summary>
        public static string MEDIAN {
            get {
                return ResourceManager.GetString("MEDIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Michaelis&apos;s curve.
        /// </summary>
        public static string MICHAELIS {
            get {
                return ResourceManager.GetString("MICHAELIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum.
        /// </summary>
        public static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parabola.
        /// </summary>
        public static string PARABOLIC {
            get {
                return ResourceManager.GetString("PARABOLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SEMST.
        /// </summary>
        public static string SEMST {
            get {
                return ResourceManager.GetString("SEMST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard error.
        /// </summary>
        public static string STD_ERROR {
            get {
                return ResourceManager.GetString("STD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Symbol.
        /// </summary>
        public static string SYMBOL {
            get {
                return ResourceManager.GetString("SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsigned integer (0 - {0}).
        /// </summary>
        public static string UINT {
            get {
                return ResourceManager.GetString("UINT", resourceCulture);
            }
        }
    }
}
