//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schicksal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schicksal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual difference.
        /// </summary>
        internal static string ACTUAL_DIFFERENCE {
            get {
                return ResourceManager.GetString("ACTUAL_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent parameter studied.
        /// </summary>
        internal static string AFFECTED_RESULT {
            get {
                return ResourceManager.GetString("AFFECTED_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic statistics metrics.
        /// </summary>
        internal static string BASIC_METRICS {
            get {
                return ResourceManager.GetString("BASIC_METRICS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Comparison {
            get {
                object obj = ResourceManager.GetObject("Comparison", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical difference.
        /// </summary>
        internal static string CRITICAL_DIFFERENCE {
            get {
                return ResourceManager.GetString("CRITICAL_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both groups must be equal for regression analysis.
        /// </summary>
        internal static string DATA_GROUP_SIZE_MISMATCH {
            get {
                return ResourceManager.GetString("DATA_GROUP_SIZE_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it&apos;s value was.
        /// </summary>
        internal static string DIFFERENCE_VALUE {
            get {
                return ResourceManager.GetString("DIFFERENCE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etc..
        /// </summary>
        internal static string ETC {
            get {
                return ResourceManager.GetString("ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export of statistic analysis results.
        /// </summary>
        internal static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Export_Picture {
            get {
                object obj = ResourceManager.GetObject("Export_Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of variance, F-criteria.
        /// </summary>
        internal static string F_CRITERIA {
            get {
                return ResourceManager.GetString("F_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string FACTOR {
            get {
                return ResourceManager.GetString("FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid column type for saving.
        /// </summary>
        internal static string INVALID_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("INVALID_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal difference occured between variants.
        /// </summary>
        internal static string MAX_DIFFERENCE {
            get {
                return ResourceManager.GetString("MAX_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal influence achieved for the factor or factor combination {0}. Probability of the first type error is {1}%..
        /// </summary>
        internal static string MAX_INFLUENCE {
            get {
                return ResourceManager.GetString("MAX_INFLUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal value was in variant {0}, it was {1}..
        /// </summary>
        internal static string MAX_VALUE {
            get {
                return ResourceManager.GetString("MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal influence achieved for the factor or factor combination {0}. Probability of the first type error is {1}%..
        /// </summary>
        internal static string MIN_INFLUENCE {
            get {
                return ResourceManager.GetString("MIN_INFLUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal value was in variant {0}, it was {1}..
        /// </summary>
        internal static string MIN_VALUE {
            get {
                return ResourceManager.GetString("MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most significat difference occured between variants.
        /// </summary>
        internal static string MOST_SIGNIFICAT_DIFFERENCE {
            get {
                return ResourceManager.GetString("MOST_SIGNIFICAT_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other differences were unsignificat..
        /// </summary>
        internal static string OTHER_UNSIGNIFICAT {
            get {
                return ResourceManager.GetString("OTHER_UNSIGNIFICAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired comparison.
        /// </summary>
        internal static string PAIRED_COMPARISON {
            get {
                return ResourceManager.GetString("PAIRED_COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string REPORT {
            get {
                return ResourceManager.GetString("REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ducring reasearch it was realized, that significat diferences were obtained between.
        /// </summary>
        internal static string SIGNIFICANT_DIFFERENCES {
            get {
                return ResourceManager.GetString("SIGNIFICANT_DIFFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors and factor combinations {0} realized to be significat with probability level {1:0.0}%.
        /// </summary>
        internal static string SIGNIFICAT {
            get {
                return ResourceManager.GetString("SIGNIFICAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significat factors and combinations.
        /// </summary>
        internal static string SIGNIFICAT_FACTORS {
            get {
                return ResourceManager.GetString("SIGNIFICAT_FACTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SUMMARY {
            get {
                return ResourceManager.GetString("SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count of observations.
        /// </summary>
        internal static string TOTAL_COUNT {
            get {
                return ResourceManager.GetString("TOTAL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ducring reasearch it was realized, that the following factors and factor combinations are not significat with probability level {0:0.0}%.
        /// </summary>
        internal static string UNSIGNIFICAT {
            get {
                return ResourceManager.GetString("UNSIGNIFICAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wariants comparison.
        /// </summary>
        internal static string VARIANTS_COMPARISON {
            get {
                return ResourceManager.GetString("VARIANTS_COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factors were varied.
        /// </summary>
        internal static string VARIED_FACTORS {
            get {
                return ResourceManager.GetString("VARIED_FACTORS", resourceCulture);
            }
        }
    }
}
