//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schicksal.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schicksal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actual difference.
        /// </summary>
        internal static string ACTUAL_DIFFERENCE {
            get {
                return ResourceManager.GetString("ACTUAL_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dependent parameter studied.
        /// </summary>
        internal static string AFFECTED_RESULT {
            get {
                return ResourceManager.GetString("AFFECTED_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на and.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic statistics metrics.
        /// </summary>
        internal static string BASIC_METRICS {
            get {
                return ResourceManager.GetString("BASIC_METRICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comparison {
            get {
                object obj = ResourceManager.GetObject("Comparison", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Critical difference.
        /// </summary>
        internal static string CRITICAL_DIFFERENCE {
            get {
                return ResourceManager.GetString("CRITICAL_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Both number sequences must be equal for regression analysis.
        /// </summary>
        internal static string DATA_SAMPLE_SIZE_MISMATCH {
            get {
                return ResourceManager.GetString("DATA_SAMPLE_SIZE_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dependency type.
        /// </summary>
        internal static string DEPENDENCY_TYPE {
            get {
                return ResourceManager.GetString("DEPENDENCY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на it&apos;s value was.
        /// </summary>
        internal static string DIFFERENCE_VALUE {
            get {
                return ResourceManager.GetString("DIFFERENCE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на etc..
        /// </summary>
        internal static string ETC {
            get {
                return ResourceManager.GetString("ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export of statistic analysis results.
        /// </summary>
        internal static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export_Picture {
            get {
                object obj = ResourceManager.GetObject("Export_Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analysis of variance, F-criteria.
        /// </summary>
        internal static string F_CRITERIA {
            get {
                return ResourceManager.GetString("F_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Factor.
        /// </summary>
        internal static string FACTOR {
            get {
                return ResourceManager.GetString("FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to determine dependency!.
        /// </summary>
        internal static string IMPOSSSIBLE_DEPENDENCY {
            get {
                return ResourceManager.GetString("IMPOSSSIBLE_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid column type for saving.
        /// </summary>
        internal static string INVALID_COLUMN_TYPE {
            get {
                return ResourceManager.GetString("INVALID_COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximal consistendy achieved for dependency type &apos;{0}&apos; equals {1}..
        /// </summary>
        internal static string MAX_CONSISTENCY {
            get {
                return ResourceManager.GetString("MAX_CONSISTENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximal difference occured between variants.
        /// </summary>
        internal static string MAX_DIFFERENCE {
            get {
                return ResourceManager.GetString("MAX_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximal influence achieved for the factor or factor combination {0}. Probability of the first type error is {1}%..
        /// </summary>
        internal static string MAX_INFLUENCE {
            get {
                return ResourceManager.GetString("MAX_INFLUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximal value was in variant {0}, it was {1}..
        /// </summary>
        internal static string MAX_VALUE {
            get {
                return ResourceManager.GetString("MAX_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimal influence achieved for the factor or factor combination {0}. Probability of the first type error is {1}%..
        /// </summary>
        internal static string MIN_INFLUENCE {
            get {
                return ResourceManager.GetString("MIN_INFLUENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimal value was in variant {0}, it was {1}..
        /// </summary>
        internal static string MIN_VALUE {
            get {
                return ResourceManager.GetString("MIN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Most significat difference occured between variants.
        /// </summary>
        internal static string MOST_SIGNIFICAT_DIFFERENCE {
            get {
                return ResourceManager.GetString("MOST_SIGNIFICAT_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create the inverse Box-Cox handler. Groups are not transformed together.
        /// </summary>
        internal static string NO_JOINT_BOX_COX {
            get {
                return ResourceManager.GetString("NO_JOINT_BOX_COX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create the inverse rank handler. Groups are not ranked together.
        /// </summary>
        internal static string NO_JOINT_RANKS {
            get {
                return ResourceManager.GetString("NO_JOINT_RANKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на other differences were unsignificat..
        /// </summary>
        internal static string OTHER_UNSIGNIFICAT {
            get {
                return ResourceManager.GetString("OTHER_UNSIGNIFICAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paired comparison.
        /// </summary>
        internal static string PAIRED_COMPARISON {
            get {
                return ResourceManager.GetString("PAIRED_COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regression dependency forumla.
        /// </summary>
        internal static string REGRESSION_DEPENDENCY {
            get {
                return ResourceManager.GetString("REGRESSION_DEPENDENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regression analysis details.
        /// </summary>
        internal static string REGRESSION_DETAILS {
            get {
                return ResourceManager.GetString("REGRESSION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regression analysis results.
        /// </summary>
        internal static string REGRESSION_RESULTS {
            get {
                return ResourceManager.GetString("REGRESSION_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report.
        /// </summary>
        internal static string REPORT {
            get {
                return ResourceManager.GetString("REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ducring reasearch it was realized, that significat diferences were obtained between.
        /// </summary>
        internal static string SIGNIFICANT_DIFFERENCES {
            get {
                return ResourceManager.GetString("SIGNIFICANT_DIFFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Factors and factor combinations {0} realized to be significat with probability level {1:0.0}%.
        /// </summary>
        internal static string SIGNIFICAT {
            get {
                return ResourceManager.GetString("SIGNIFICAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Significat factors and combinations.
        /// </summary>
        internal static string SIGNIFICAT_FACTORS {
            get {
                return ResourceManager.GetString("SIGNIFICAT_FACTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summary.
        /// </summary>
        internal static string SUMMARY {
            get {
                return ResourceManager.GetString("SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total count of observations.
        /// </summary>
        internal static string TOTAL_COUNT {
            get {
                return ResourceManager.GetString("TOTAL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ducring reasearch it was realized, that the following factors and factor combinations are not significat with probability level {0:0.0}%.
        /// </summary>
        internal static string UNSIGNIFICAT {
            get {
                return ResourceManager.GetString("UNSIGNIFICAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wariants comparison.
        /// </summary>
        internal static string VARIANTS_COMPARISON {
            get {
                return ResourceManager.GetString("VARIANTS_COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Factors were varied.
        /// </summary>
        internal static string VARIED_FACTORS {
            get {
                return ResourceManager.GetString("VARIED_FACTORS", resourceCulture);
            }
        }
    }
}
