//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schicksal.Helm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schicksal.Helm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap about_logo {
            get {
                object obj = ResourceManager.GetObject("about_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap About_Picture {
            get {
                object obj = ResourceManager.GetObject("About_Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string ANALYZE {
            get {
                return ResourceManager.GetString("ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of covariance.
        /// </summary>
        internal static string ANCOVA {
            get {
                return ResourceManager.GetString("ANCOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of variance.
        /// </summary>
        internal static string ANOVA {
            get {
                return ResourceManager.GetString("ANOVA", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_left_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_right_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic statistics.
        /// </summary>
        internal static string BASIC_STATISTICS {
            get {
                return ResourceManager.GetString("BASIC_STATISTICS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap column_chart {
            get {
                object obj = ResourceManager.GetObject("column_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison in pairs.
        /// </summary>
        internal static string COMPARISON {
            get {
                return ResourceManager.GetString("COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string COUNT {
            get {
                return ResourceManager.GetString("COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new table.
        /// </summary>
        internal static string CREATE_NEW_TABLE {
            get {
                return ResourceManager.GetString("CREATE_NEW_TABLE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap disk_blue {
            get {
                object obj = ResourceManager.GetObject("disk_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distribution.
        /// </summary>
        internal static string DISTRIBUTION {
            get {
                return ResourceManager.GetString("DISTRIBUTION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name {0} is not unique.
        /// </summary>
        internal static string DUPLICATE_COLUMN {
            get {
                return ResourceManager.GetString("DUPLICATE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty column name.
        /// </summary>
        internal static string EMPTY_COLUMNS {
            get {
                return ResourceManager.GetString("EMPTY_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive color.
        /// </summary>
        internal static string EXCLUSIVE_COLOR {
            get {
                return ResourceManager.GetString("EXCLUSIVE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisher distribution.
        /// </summary>
        internal static string FISHER {
            get {
                return ResourceManager.GetString("FISHER", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear_preferences {
            get {
                object obj = ResourceManager.GetObject("gear_preferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string IMPORT {
            get {
                return ResourceManager.GetString("IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence interval.
        /// </summary>
        internal static string INTERVAL {
            get {
                return ResourceManager.GetString("INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        internal static string LAST_FILES {
            get {
                return ResourceManager.GetString("LAST_FILES", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap line_chart {
            get {
                object obj = ResourceManager.GetObject("line_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo_24 {
            get {
                object obj = ResourceManager.GetObject("Logo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        internal static string MEAN {
            get {
                return ResourceManager.GetString("MEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New table.
        /// </summary>
        internal static string NEW_TABLE {
            get {
                return ResourceManager.GetString("NEW_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No columns specified.
        /// </summary>
        internal static string NO_COLUMNS {
            get {
                return ResourceManager.GetString("NO_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open system folder.
        /// </summary>
        internal static string OPEN_SYSTEM_FOLDER {
            get {
                return ResourceManager.GetString("OPEN_SYSTEM_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SAVE_AS {
            get {
                return ResourceManager.GetString("SAVE_AS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save_as_icon {
            get {
                object obj = ResourceManager.GetObject("save_as_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes in table {0}?.
        /// </summary>
        internal static string SAVE_FILE_CONFIRM {
            get {
                return ResourceManager.GetString("SAVE_FILE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SCHICKSAL_DATA_FILES {
            get {
                return ResourceManager.GetString("SCHICKSAL_DATA_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significat color.
        /// </summary>
        internal static string SIGNIFICAT_COLOR {
            get {
                return ResourceManager.GetString("SIGNIFICAT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard tables.
        /// </summary>
        internal static string STANDARD_TABLES {
            get {
                return ResourceManager.GetString("STANDARD_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string STATISTICS {
            get {
                return ResourceManager.GetString("STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard error.
        /// </summary>
        internal static string STD_ERROR {
            get {
                return ResourceManager.GetString("STD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student distribution.
        /// </summary>
        internal static string STUDENT {
            get {
                return ResourceManager.GetString("STUDENT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap table_sql {
            get {
                object obj = ResourceManager.GetObject("table_sql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string WINDOWS {
            get {
                return ResourceManager.GetString("WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols [,+] are not allowed in column names.
        /// </summary>
        internal static string WRONG_COLUMN_NAME {
            get {
                return ResourceManager.GetString("WRONG_COLUMN_NAME", resourceCulture);
            }
        }
    }
}
