//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schicksal.Helm.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schicksal.Helm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About....
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about_logo {
            get {
                object obj = ResourceManager.GetObject("about_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About_Picture {
            get {
                object obj = ResourceManager.GetObject("About_Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analyze.
        /// </summary>
        internal static string ANALYZE {
            get {
                return ResourceManager.GetString("ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analysis of covariance.
        /// </summary>
        internal static string ANCOVA {
            get {
                return ResourceManager.GetString("ANCOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analysis of variance.
        /// </summary>
        internal static string ANOVA {
            get {
                return ResourceManager.GetString("ANOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_left_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_right_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic statistics.
        /// </summary>
        internal static string BASIC_STATISTICS {
            get {
                return ResourceManager.GetString("BASIC_STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap column_chart {
            get {
                object obj = ResourceManager.GetObject("column_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comparison in pairs.
        /// </summary>
        internal static string COMPARISON {
            get {
                return ResourceManager.GetString("COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count.
        /// </summary>
        internal static string COUNT {
            get {
                return ResourceManager.GetString("COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new table.
        /// </summary>
        internal static string CREATE_NEW_TABLE {
            get {
                return ResourceManager.GetString("CREATE_NEW_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk_blue {
            get {
                object obj = ResourceManager.GetObject("disk_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на distribution.
        /// </summary>
        internal static string DISTRIBUTION {
            get {
                return ResourceManager.GetString("DISTRIBUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dot_chart {
            get {
                object obj = ResourceManager.GetObject("dot_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column name {0} is not unique.
        /// </summary>
        internal static string DUPLICATE_COLUMN {
            get {
                return ResourceManager.GetString("DUPLICATE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty column name.
        /// </summary>
        internal static string EMPTY_COLUMNS {
            get {
                return ResourceManager.GetString("EMPTY_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exclusive color.
        /// </summary>
        internal static string EXCLUSIVE_COLOR {
            get {
                return ResourceManager.GetString("EXCLUSIVE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        internal static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fisher distribution.
        /// </summary>
        internal static string FISHER {
            get {
                return ResourceManager.GetString("FISHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear_preferences {
            get {
                object obj = ResourceManager.GetObject("gear_preferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        internal static string IMPORT {
            get {
                return ResourceManager.GetString("IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confidence interval.
        /// </summary>
        internal static string INTERVAL {
            get {
                return ResourceManager.GetString("INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent files.
        /// </summary>
        internal static string LAST_FILES {
            get {
                return ResourceManager.GetString("LAST_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line_chart {
            get {
                object obj = ResourceManager.GetObject("line_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_24 {
            get {
                object obj = ResourceManager.GetObject("Logo_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mean.
        /// </summary>
        internal static string MEAN {
            get {
                return ResourceManager.GetString("MEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        internal static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New table.
        /// </summary>
        internal static string NEW_TABLE {
            get {
                return ResourceManager.GetString("NEW_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No columns specified.
        /// </summary>
        internal static string NO_COLUMNS {
            get {
                return ResourceManager.GetString("NO_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open system folder.
        /// </summary>
        internal static string OPEN_SYSTEM_FOLDER {
            get {
                return ResourceManager.GetString("OPEN_SYSTEM_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save As.
        /// </summary>
        internal static string SAVE_AS {
            get {
                return ResourceManager.GetString("SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_as_icon {
            get {
                object obj = ResourceManager.GetObject("save_as_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save changes in table {0}?.
        /// </summary>
        internal static string SAVE_FILE_CONFIRM {
            get {
                return ResourceManager.GetString("SAVE_FILE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Significat color.
        /// </summary>
        internal static string SIGNIFICAT_COLOR {
            get {
                return ResourceManager.GetString("SIGNIFICAT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard tables.
        /// </summary>
        internal static string STANDARD_TABLES {
            get {
                return ResourceManager.GetString("STANDARD_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        internal static string STATISTICS {
            get {
                return ResourceManager.GetString("STATISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard error.
        /// </summary>
        internal static string STD_ERROR {
            get {
                return ResourceManager.GetString("STD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Student distribution.
        /// </summary>
        internal static string STUDENT {
            get {
                return ResourceManager.GetString("STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string TABLE_EDIT {
            get {
                return ResourceManager.GetString("TABLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_sql {
            get {
                object obj = ResourceManager.GetObject("table_sql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows.
        /// </summary>
        internal static string WINDOWS {
            get {
                return ResourceManager.GetString("WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Symbols [,+] are not allowed in column names.
        /// </summary>
        internal static string WRONG_COLUMN_NAME {
            get {
                return ResourceManager.GetString("WRONG_COLUMN_NAME", resourceCulture);
            }
        }
    }
}
